AWSTemplateFormatVersion: "2010-09-09"
Description: Simple VPC Creation Template

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MySimpleVPC

Outputs:
  VPCId:
    Description: ID of the created VPC
    Value: !Ref MyVPC
